<?php include 'header.php'; ?>

	<div class="text-bg-header">
	
		<div class="content-unpadded">
		
			<div id="breadcrumb">
			
				<ul>
				
					<li>
						<a href="http://ethicalswitch.com">Home</a>
					</li> > 
				
					<li>
						<a href="ethical-power">Ethical Power</a>
					</li> > 
				
					<li>
						<a href="power-switch-powershop">Powershop</a>
					</li> > 
				
					<li>
						Thanks for Getting in Touch
					</li> 
			
				</ul>
				
			</div>
		
			<div class="text-bg-header-h2">
			
				<h2>Thanks for Getting in Touch!</h2>
			
			</div>
			
		</div>
		
	</div>
	
	<div class="text-pages">
	
		<?php
		 
		if(isset($_POST['email'])) {
		 
			 
		 
			// EDIT THE 2 LINES BELOW AS REQUIRED
		 
			$email_to = "hello@ethicalswitch.com,compare@powershop.com.au";
		 
			$email_subject = "Bill Compare Request";
		 
			 
		 
			 
		 
			function died($error) {
		 
				// your error code can go here
		 
				echo "Sorry, there was a problem with the form:<br /><br /> ";
		 
				echo $error."<br /><br />";
		 
				echo "Please go back to the form.<br /><br />";
		 
				die();
		 
			}
		 
			 
		 
			// validation expected data exists
		 
			if(!isset($_POST['name']) ||
		 
				!isset($_POST['email'])) {
		 
				died('Sorry, there was a problem with the form:');       
		 
			}
		 
			 
		 
			$name = $_POST['name']; // required
		 
			$email_from = $_POST['email']; // required
		 
			$telephone = $_POST['telephone']; // not required
		 
			$message = $_POST['message']; // required
		 
			 
		 
			$error_message = "";
		 
			$email_exp = '/^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/';
		 
		  if(!preg_match($email_exp,$email_from)) {
		 
			$error_message .= "The Email Address you entered doesn't seem to be valid!.<br />";
		 
		  }
		 
			$string_exp = "/^[A-Za-z .'-]+$/";
		 
		  if(!preg_match($string_exp,$name)) {
		 
			$error_message .= "You didn't enter a name!<br />";
		 
		  }
		 
		  if(strlen($error_message) > 0) {
		 
			died($error_message);
		 
		  }
		 
			$email_message = "Ethical Switch Bill Compare Request:\nThis lead was generated by Ethical Switch\n\n";
		 
			 
		 
			function clean_string($string) {
		 
			  $bad = array("content-type","bcc:","to:","cc:","href");
		 
			  return str_replace($bad,"",$string);
		 
			}
		 
			 
		 
			$email_message .= "Name: ".clean_string($name)."\n";
		 
			$email_message .= "Email: ".clean_string($email_from)."\n";
		 
			$email_message .= "Telephone: ".clean_string($telephone)."\n";
		 
			$email_message .= "Any Other Questions?: ".clean_string($message)."\n";
		 
			 
		 
			 
		 
		// create email headers
		 
		$headers = 'From: '.$email_from."\r\n".
		 
		'Reply-To: '.$email_from."\r\n" .
		 
		'X-Mailer: PHP/' . phpversion();
		 
		@mail($email_to, $email_subject, $email_message, $headers);  
		 
		?>
		 
		 
		 
		<!-- include your own success html here -->
		 
		 
		 
		<p class="center">We'll be in touch with your bill compare as soon as we can.</p>
		 
		 
		 
		<?php
		 
		}
		 
		?>

	</div>
<?php include 'footer.php'; ?>